name: Update gist
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    environment: Main
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify a stable Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.26.0 urllib3==1.26.7

      - name: Update gist
        env:
          HOYO_UID: ${{ secrets.HOYO_UID }}
          HOYO_TOKEN: ${{ secrets.HOYO_TOKEN }}
          HOYO_TMID: ${{ secrets.HOYO_TMID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: python main.py
