name: Update gist
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    environment: Main
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Pip install"
        run: pip install -r requirements.txt

      - name: "Update gist"
        env:
          HOYO_UID: ${{ secrets.HOYO_UID }}
          HOYO_TOKEN: ${{ secrets.HOYO_TOKEN }}
          HOYO_TMID: ${{ secrets.HOYO_TMID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ad0ca0c977d91b30b1e4f48fd2b71ba7
        run: python main.py
